[toolchain]
    channel="nightly-2026-04-21"
    components=[
        "rust-src",      # Makes the source code of the standard library available for compilation
        "rustfmt",
        "rustc",
        "rust-std",
        "clippy",
        "cargo",
        "rust-analyzer",
    ]
    targets=["wasm32-unknown-unknown"]
