[package]
    authors.workspace=true
    description="Database code for VOWLGrapher"
    edition.workspace=true
    keywords=["rdf", "graph", "sparql", "datafusion"]
    license-file.workspace=true
    name="vowlgrapher-database"
    readme="README.md"
    repository.workspace=true
    version.workspace=true

[lib]
    crate-type=["cdylib", "rlib"]

[lints]
    workspace=true

[dependencies]
    env_logger.workspace=true
    fluent-uri.workspace=true
    futures.workspace=true
    grapher.workspace=true
    horned-owl.workspace=true
    log.workspace=true
    oxrdf.workspace=true
    rayon.workspace=true
    rdf-fusion.workspace=true
    reqwest={workspace=true, features=["stream"]}
    smallvec.workspace=true
    strum.workspace=true
    tempfile.workspace=true
    test-generator.workspace=true
    tokio.workspace=true
    unescape_zero_copy.workspace=true
    uuid.workspace=true
    vowlgrapher-parser={path="../parser"}
    vowlgrapher-serializer={path="../serializer"}
    vowlgrapher-sparql-queries={path="../sparql_queries"}
    vowlgrapher-util={path="../util", features=["server"]}

[dev-dependencies]
    anyhow.workspace=true
    grapher={workspace=true, features=["test-utils"]}
    sovs-parser={git="https://github.com/WebVOWL/sovs-parser", version="0.1.0", features=[
        "test-suite",
    ]}
