PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vowlr: <http://www.example.com/iri#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
            SELECT DISTINCT ?id ?nodeType ?target ?label
            WHERE {
                {
                # AnonymousClass
                {
                    ?id a owl:Class .
                    FILTER(!isIRI(?id))
                }
                UNION
                {
                    ?id a owl:Restriction .
                    FILTER(!isIRI(?id))
                }

                FILTER NOT EXISTS {
                    ?named rdfs:subClassOf ?id .
                    FILTER(isIRI(?named))
                    {
                        { ?id owl:unionOf ?u }
                        UNION
                        { ?id owl:intersectionOf ?i }
                        UNION
                        { ?id owl:complementOf ?c }
                        UNION
                        { ?id owl:disjointUnionOf ?d }
                    }
                }

                BIND("blanknode" AS ?nodeType)
                } UNION {
                # owl:Class
                ?id a owl:Class .
                FILTER(isIRI(?id))
                BIND(owl:Class AS ?nodeType)
                } UNION {
                # owl:complementOf
                {
                    ?id owl:complementOf ?target .
                    FILTER NOT EXISTS {
                        ?named rdfs:subClassOf ?id .
                        FILTER(isIRI(?named))
                        FILTER(!isIRI(?id))
                    }
                }
                UNION
                {
                    ?named rdfs:subClassOf ?anon .
                    FILTER(isIRI(?named))
                    FILTER(!isIRI(?anon))
                    ?anon owl:complementOf ?target .
                    BIND(?named AS ?id)
                }
                BIND(owl:complementOf AS ?nodeType)
                } UNION {
                ?id a owl:DeprecatedClass .
                BIND(owl:DeprecatedClass AS ?nodeType)
                } UNION {
                ?id owl:equivalentClass ?target
                BIND(owl:equivalentClass AS ?nodeType)
                } UNION {
                # owl:disjointUnionOf
                {
                    ?id owl:disjointUnionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    FILTER NOT EXISTS {
                        ?named rdfs:subClassOf ?id .
                        FILTER(isIRI(?named))
                        FILTER(!isIRI(?id))
                    }
                }
                UNION
                {
                    ?named rdfs:subClassOf ?anon .
                    FILTER(isIRI(?named))
                    FILTER(!isIRI(?anon))
                    ?anon owl:disjointUnionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    BIND(?named AS ?id)
                }
                BIND(owl:disjointUnionOf AS ?nodeType)
                } UNION {
                # owl:intersectionOf
                {
                    ?id owl:intersectionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    FILTER NOT EXISTS {
                        ?named rdfs:subClassOf ?id .
                        FILTER(isIRI(?named))
                        FILTER(!isIRI(?id))
                    }
                }
                UNION
                {
                    ?named rdfs:subClassOf ?anon .
                    FILTER(isIRI(?named))
                    FILTER(!isIRI(?anon))
                    ?anon owl:intersectionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    BIND(?named AS ?id)
                }
                BIND(owl:intersectionOf AS ?nodeType)
                } UNION {
                ?id a owl:Thing .
                BIND(owl:Thing AS ?nodeType)
                } UNION {
                # owl:unionOf
                {
                    ?id owl:unionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    FILTER NOT EXISTS {
                        ?named rdfs:subClassOf ?id .
                        FILTER(isIRI(?named))
                        FILTER(!isIRI(?id))
                    }
                }
                UNION
                {
                    ?named rdfs:subClassOf ?anon .
                    FILTER(isIRI(?named))
                    FILTER(!isIRI(?anon))
                    ?anon owl:unionOf/rdf:rest*/rdf:first ?target .
                    FILTER(?target != rdf:nil)
                    BIND(?named AS ?id)
                }
                BIND(owl:unionOf AS ?nodeType)
                } UNION {
                ?id a owl:real .
                BIND(owl:real AS ?nodeType)
                } UNION {
                ?id a owl:rational .
                BIND(owl:rational AS ?nodeType)
                } UNION {
                ?id a owl:DatatypeProperty .
                BIND(owl:DatatypeProperty AS ?nodeType)
                } UNION {
                ?id owl:disjointWith ?target
                BIND(owl:disjointWith AS ?nodeType)
                } UNION {
                ?id a owl:DeprecatedProperty .
                BIND(owl:DeprecatedProperty AS ?nodeType)
                } UNION {
                ?id owl:inverseOf ?target .
                BIND(owl:inverseOf AS ?nodeType)
                } UNION {
                ?id a owl:ObjectProperty
                BIND(owl:ObjectProperty AS ?nodeType)
                } UNION {
                # Cardinalities
                { ?id owl:onProperty ?target . BIND(owl:onProperty AS ?nodeType) }
                UNION
                { ?id owl:someValuesFrom ?target . BIND(owl:someValuesFrom AS ?nodeType) }
                UNION
                { ?id owl:allValuesFrom ?target . BIND(owl:allValuesFrom AS ?nodeType) }
                UNION
                { ?id owl:hasSelf ?target . BIND(owl:hasSelf AS ?nodeType) }
                UNION
                { ?id owl:hasValue ?target . BIND(owl:hasValue AS ?nodeType) }
                UNION
                { ?id owl:minCardinality ?target . BIND(owl:minCardinality AS ?nodeType) }
                UNION
                { ?id owl:maxCardinality ?target . BIND(owl:maxCardinality AS ?nodeType) }
                UNION
                { ?id owl:cardinality ?target . BIND(owl:cardinality AS ?nodeType) }
                UNION
                { ?id owl:minQualifiedCardinality ?target . BIND(owl:minQualifiedCardinality AS ?nodeType) }
                UNION
                { ?id owl:maxQualifiedCardinality ?target . BIND(owl:maxQualifiedCardinality AS ?nodeType) }
                UNION
                { ?id owl:qualifiedCardinality ?target . BIND(owl:qualifiedCardinality AS ?nodeType) }
                UNION
                { ?id owl:onClass ?target . BIND(owl:onClass AS ?nodeType) }
                UNION
                { ?id owl:onDataRange ?target . BIND(owl:onDataRange AS ?nodeType) }
                } UNION {
                ?id rdf:Property ?target
                BIND(rdf:Property AS ?nodeType)
                } UNION {
                ?id a rdfs:Class .
                FILTER(?id != owl:Class)
                FILTER NOT EXISTS { ?id a owl:Class }
                BIND(rdfs:Class AS ?nodeType)
                } UNION {
                ?id a rdfs:Literal .
                BIND(rdfs:Literal AS ?nodeType)
                } UNION {
                ?id a rdfs:Resource .
                FILTER(isIRI(?id) || isBlank(?id))
                BIND(rdfs:Resource AS ?nodeType)
                } UNION {
                ?id a rdfs:Datatype .
                BIND(rdfs:Datatype AS ?nodeType)
                } UNION {
                ?id rdfs:subClassOf ?target .
                FILTER NOT EXISTS { ?target owl:unionOf ?u }
                FILTER NOT EXISTS { ?target owl:intersectionOf ?i }
                FILTER NOT EXISTS { ?target owl:complementOf ?c }
                FILTER NOT EXISTS { ?target owl:disjointUnionOf ?d }
                BIND(rdfs:subClassOf AS ?nodeType)
                } UNION {
                ?id a owl:TransitiveProperty
                BIND(owl:TransitiveProperty AS ?nodeType)
            } UNION {
                ?id a owl:FunctionalProperty
                BIND(owl:FunctionalProperty AS ?nodeType)
            } UNION {
                ?id a owl:InverseFunctionalProperty
                BIND(owl:InverseFunctionalProperty AS ?nodeType)
            } UNION {
                ?id a owl:ReflexiveProperty
                BIND(owl:ReflexiveProperty AS ?nodeType)
            } UNION {
                ?id a owl:IrreflexiveProperty
                BIND(owl:IrreflexiveProperty AS ?nodeType)
            } UNION {
                ?id a owl:SymmetricProperty
                BIND(owl:SymmetricProperty AS ?nodeType)
            } UNION {
                ?id a owl:AsymmetricProperty
                BIND(owl:AsymmetricProperty AS ?nodeType)
            } UNION {
                ?id a owl:hasKey
                BIND(owl:hasKey AS ?nodeType)
            } UNION {
            # Get the base URI of the document.
            ?id a owl:Ontology .
            BIND(owl:Ontology AS ?nodeType)
            } UNION {
            # Get the base URI of the document.
            ?id xml:base ?base .
            BIND(xml:base AS ?nodeType)
            } UNION {
            # Flatten collections. Currently only supports select OWL types.
            ?id ?nodeType ?intermediate .
            ?intermediate rdf:first ?firstItem .
            ?intermediate rdf:rest*/rdf:first ?target .
            FILTER(?nodeType IN (
                owl:oneOf
            ))

            # 6. Safety: Remove nil to avoid phantom edges
            # FILTER(?label != rdf:nil)
            } UNION {
        # Find the domain and range of any property, and restructure so they appear as singular triples
        {
            VALUES ?property {
                owl:DeprecatedProperty
                owl:DatatypeProperty
                owl:ObjectProperty
                rdf:Property
            }
            ?nodeType a ?property .
            ?nodeType rdfs:range ?target .
            ?nodeType rdfs:domain ?id .
        } UNION {
            VALUES ?property {
                owl:DeprecatedProperty
                owl:DatatypeProperty
                owl:ObjectProperty
                rdf:Property
            }
            ?nodeType a ?property .
            ?nodeType rdfs:range ?target .
            FILTER NOT EXISTS { ?nodeType rdfs:domain ?x }
            BIND(IF(?property = owl:DatatypeProperty, rdfs:Literal, owl:Thing) AS ?id)
        } UNION {
            VALUES ?property {
                owl:DeprecatedProperty
                owl:DatatypeProperty
                owl:ObjectProperty
                rdf:Property
            }
            ?nodeType a ?property .
            ?nodeType rdfs:domain ?id .
            FILTER NOT EXISTS { ?nodeType rdfs:range ?x }
            BIND(IF(?property = owl:DatatypeProperty, rdfs:Literal, owl:Thing) AS ?target)
        } UNION {
            VALUES ?property {
                owl:DeprecatedProperty
                owl:DatatypeProperty
                owl:ObjectProperty
                rdf:Property
            }
            ?nodeType a ?property .
            FILTER NOT EXISTS { ?nodeType rdfs:range ?x }
            FILTER NOT EXISTS { ?nodeType rdfs:domain ?x }
            BIND(owl:Thing AS ?id)
            BIND(IF(?property = owl:DatatypeProperty, rdfs:Literal, owl:Thing) AS ?target)
        }
        } UNION {
            # Generic, deprecated OWL elements.
            ?id owl:deprecated ?target .
            FILTER(?target = "true"^^xsd:boolean || lcase(str(?target)) = "true")
            BIND(owl:deprecated AS ?nodeType)
            } UNION {
            # Find labels for elements.
            OPTIONAL { ?id rdfs:label ?theLabel }
            OPTIONAL { ?id rdf:resource ?resLabel }
            OPTIONAL { ?id rdf:ID ?idLabel }
            BIND (
                COALESCE(
                    IF( BOUND(?theLabel), ?theLabel, 1/0 ),
                    IF( BOUND(?resLabel), ?resLabel, 1/0 ),
                    IF( BOUND(?idLabel), ?idLabel, 1/0 ),
                    ""
                ) AS ?label
            )
            }
                BIND(
                    IF(?nodeType = owl:Ontology, 0,
                        IF(?nodeType = owl:Class, 1, 2)
                    )
                    AS ?weight
                )
            }
            ORDER BY ?weight
