//! Automatically write SPARQL query snippets to a file.

use std::fs;

use vowlgrapher_sparql_queries::prelude::DEFAULT_QUERY;

/// Writes the default query to a file.
fn main() -> std::io::Result<()> {
    let query = DEFAULT_QUERY.replace("GRAPH <{GRAPH_IRI}>", "");
    fs::write(
        "crates/sparql_queries/src/reference/default.rq",
        format!(
            "# Generated by {} v{}\n\n{query}",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION")
        )
        .as_bytes(),
    )?;
    Ok(())
}
