[package]
    authors=["TheRealMorgenfrue"]
    description="Run this workspace natively, i.e., without a browser."
    edition.workspace=true
    keywords.workspace=true
    license-file.workspace=true
    name="perfdebugger"
    repository.workspace=true
    version.workspace=true

[lints]
    workspace=true

[dependencies]
    env_logger.workspace=true
    grapher={workspace=true, features=["native", "static"]}
    log.workspace=true
    tokio.workspace=true
    vowlgrapher-database={path="../database"}
    vowlgrapher-sparql-queries={path="../sparql_queries"}
